2020-08-08 02:19:58.642 [error] <0.639.0>@Elixir.STPuzzleCoordinator.ConfigHandler:-init/1-fun-3-:207 CRASH REPORT Process <0.639.0> with 1 neighbours crashed with reason: bad argument in call to ets:insert([#{<<"b">> => 0.833333,<<"g">> => 0.833333,<<"r">> => 0.833333},#{<<"b">> => 0.0,<<"g">> => 0.0,...},...], {bridges,#Ref<0.575077859.2373844993.54067>}) in 'Elixir.STPuzzleCoordinator.ConfigHandler':'-init/1-fun-3-'/2 line 207
2020-08-08 02:19:58.644 [error] <0.478.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at undefined exit with reason {'EXIT',{{badmatch,{error,{badarg,[{ets,insert,[[#{<<"b">> => 0.833333,<<"g">> => 0.833333,<<"r">> => 0.833333},#{<<"b">> => 0.0,<<"g">> => 0.0,<<"r">> => 0.0},#{<<"b">> => 1.0,<<"g">> => 1.0,<<"r">> => 1.0},#{<<"b">> => 0.666667,<<"g">> => 0.666667,<<"r">> => 0.666667},#{<<"b">> => 0.25,<<"g">> => 1.0,<<"r">> => 0.25},#{<<"b">> => 1.0,<<"g">> => 1.0,<<"r">> => 1.0},#{<<"b">> => 0.666667,<<"g">> => 0.666667,<<"r">> => 0.666667},#{<<"b">> => 0.75,<<"g">> => 0.75,<<"r">> => 0.75},#{<<"b">> => 0.25,...},...],...],...},...]}}},...}} in context start_error
2020-08-08 02:19:58.647 [error] <0.476.0> CRASH REPORT Process <0.476.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.STPuzzleCoordinator',{'EXIT',{{badmatch,{error,{badarg,[{ets,insert,[[#{<<"b">> => 0.833333,<<"g">> => 0.833333,<<"r">> => 0.833333},#{<<"b">> => 0.0,<<"g">> => 0.0,<<"r">> => 0.0},#{<<"b">> => 1.0,<<"g">> => 1.0,<<"r">> => 1.0},#{<<"b">> => 0.666667,<<"g">> => 0.666667,<<"r">> => 0.666667},#{<<"b">> => 0.25,<<"g">> => 1.0,<<"r">> => 0.25},#{<<"b">> => 1.0,<<"g">> => 1.0,<<"r">> => 1.0},#{<<"b">> => 0.666667,<<"g">> => 0.666667,<<"r">> => 0.666667},...],...],...},...]}}},...}}}},...} in application_master:init/4 line 138
2020-08-08 02:25:59.751 [error] <0.619.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 gen_server 'Elixir.STPuzzleCoordinator.ConfigHandler' terminated with reason: no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224
2020-08-08 02:25:59.953 [error] <0.619.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 CRASH REPORT Process <0.619.0> with 0 neighbours crashed with reason: no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224
2020-08-08 02:25:59.953 [error] <0.462.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at <0.619.0> exit with reason no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224 in context child_terminated
2020-08-08 02:25:59.954 [error] <0.462.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at <0.619.0> exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.602.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_info,2,[{file,"supervisor.erl"},{line,574}]},...]}} in context start_error
2020-08-08 02:25:59.955 [error] <0.462.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.619.0>} exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.602.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_cast,2,[{file,"supervisor.erl"},{line,557}]},...]}} in context start_error
2020-08-08 02:25:59.956 [error] <0.462.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.619.0>} exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.602.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_cast,2,[{file,"supervisor.erl"},{line,557}]},...]}} in context start_error
2020-08-08 02:25:59.956 [error] <0.462.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.619.0>} exit with reason reached_max_restart_intensity in context shutdown
2020-08-08 02:26:01.071 [error] <0.682.0> CRASH REPORT Process <0.682.0> with 0 neighbours exited with reason: {{{{{{badmatch,nil},[{'Elixir.STPuzzleCoordinator.ConfigHandler',handle_call,3,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,224}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[{global,'Elixir.STPuzzleCoordinator.ConfigHandler'},{get_colors,nil},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',...}},...},...}
2020-08-08 02:26:01.159 [error] <0.682.0> Cowboy stream 11 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.636.0> had its request process exit with reason: {{{{{badmatch,nil},[{'Elixir.STPuzzleCoordinator.ConfigHandler',handle_call,3,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,224}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[{global,'Elixir.STPuzzleCoordinator.ConfigHandler'},{get_colors,nil},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',call,...}},...}
2020-08-08 02:26:04.967 [error] <0.476.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.PuzzlespaceWeb.Endpoint.HTTP']}]) at <0.600.0> exit with reason killed in context shutdown_error
2020-08-08 02:29:22.157 [error] <0.613.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 gen_server 'Elixir.STPuzzleCoordinator.ConfigHandler' terminated with reason: no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224
2020-08-08 02:29:22.387 [error] <0.613.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 CRASH REPORT Process <0.613.0> with 0 neighbours crashed with reason: no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224
2020-08-08 02:29:22.387 [error] <0.456.0>@Elixir.STPuzzleCoordinator.ConfigHandler:handle_call:224 Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at <0.613.0> exit with reason no match of right hand value nil in 'Elixir.STPuzzleCoordinator.ConfigHandler':handle_call/3 line 224 in context child_terminated
2020-08-08 02:29:22.389 [error] <0.456.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at <0.613.0> exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.596.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_info,2,[{file,"supervisor.erl"},{line,574}]},...]}} in context start_error
2020-08-08 02:29:22.392 [error] <0.456.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.613.0>} exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.596.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_cast,2,[{file,"supervisor.erl"},{line,557}]},...]}} in context start_error
2020-08-08 02:29:22.392 [error] <0.456.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.613.0>} exit with reason {'EXIT',{{badmatch,{error,{already_started,<0.596.0>}}},[{'Elixir.STPuzzleCoordinator',initialize,0,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,restart,3,[{file,"supervisor.erl"},{line,768}]},{supervisor,restart,2,[{file,"supervisor.erl"},{line,723}]},{supervisor,handle_cast,2,[{file,"supervisor.erl"},{line,557}]},...]}} in context start_error
2020-08-08 02:29:22.392 [error] <0.456.0> Supervisor 'Elixir.Puzzlespace.Supervisor' had child 'Elixir.STPuzzleCoordinator' started with 'Elixir.STPuzzleCoordinator':initialize() at {restarting,<0.613.0>} exit with reason reached_max_restart_intensity in context shutdown
2020-08-08 02:29:23.164 [error] <0.665.0> CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: {{{{{{badmatch,nil},[{'Elixir.STPuzzleCoordinator.ConfigHandler',handle_call,3,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,224}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[{global,'Elixir.STPuzzleCoordinator.ConfigHandler'},{get_colors,<<"bridges">>},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',...}},...},...}
2020-08-08 02:29:23.197 [error] <0.665.0> Cowboy stream 13 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.624.0> had its request process exit with reason: {{{{{badmatch,nil},[{'Elixir.STPuzzleCoordinator.ConfigHandler',handle_call,3,[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,224}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{'Elixir.GenServer',call,[{global,'Elixir.STPuzzleCoordinator.ConfigHandler'},{get_colors,<<"bridges">>},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',...}},...}
2020-08-08 02:29:27.408 [error] <0.470.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.PuzzlespaceWeb.Endpoint.HTTP']}]) at <0.594.0> exit with reason killed in context shutdown_error
2020-08-08 16:39:48.589 [error] <0.610.0> CRASH REPORT Process <0.610.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,<<"is nil">>}},[{'Elixir.PuzzlespaceWeb.PageController',list_saves,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,70}]},{'Elixir.PuzzlespaceWeb.PageController',action,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,1}]},{'Elixir.PuzzlespaceWeb.PageController',phoenix_controller_pipeline,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,1}]},{'Elixir.Phoenix.Router',...},...]},...},...},...}
2020-08-08 16:39:48.798 [error] <0.610.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.609.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,<<"is nil">>}},[{'Elixir.PuzzlespaceWeb.PageController',list_saves,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,70}]},{'Elixir.PuzzlespaceWeb.PageController',action,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,1}]},{'Elixir.PuzzlespaceWeb.PageController',phoenix_controller_pipeline,2,[{file,"lib/puzzlespace_web/controllers/page_controller.ex"},{line,1}]},{'Elixir.Phoenix.Router',...},...]},...},...}
2020-08-09 19:30:55.028 [error] <0.879.0> CRASH REPORT Process <0.879.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<...>>,...},...}},...},...},...},...},...},...}
2020-08-09 19:30:55.405 [error] <0.879.0> Cowboy stream 4 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.866.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...},...}
